// Store Course Card Data
export const CourseCardData = [
  // ===== HTML (10) =====
  {
    id: "html-1",
    title: "Mastering HTML5 : From Beginner to Advanced Web Development",
    category: "HTML",
    instructor: "Harray",
    lessons: 6,
    duration: "3h 11m",
    features: ["Responsive Design", "Semantic Tags", "Forms & Validation"],
    price: "$49",
    rating: 4.6,
    video: "https://www.youtube.com/watch?v=BsDoLVMnmZs",
  },
  {
    id: "html-2",
    title: "HTML for Beginners",
    category: "HTML",
    instructor: "Shradha Khanpara",
    lessons: 9,
    duration: "2h 6m",
    features: ["Basics", "Headings", "Lists"],
    price: "$39",
    rating: 4.4,
    video:
      " https://www.youtube.com/watch?v=HcOc7P5BMi4&list=PLfqMhTWNBTe0PY9xunOzsP5kmYIz2Hu7i",
  },
  {
    id: "html-3",
    title: "Form Basics",
    category: "HTML",
    instructor: "Harry",
    lessons: 3,
    duration: "14m",
    features: ["Forms", "Input tags", "Accessibility"],
    price: "$55",
    rating: 4.7,
    video: "https://www.youtube.com/watch?v=tLBlhp0SA_0",
  },
  {
    id: "html-4",
    title: "HTML Projects for Practice",
    category: "HTML",
    instructor: "Harry",
    lessons: 2,
    duration: "14m",
    features: ["Form", "Practise"],
    price: "$50",
    rating: 4.5,
    video: "https://www.youtube.com/watch?v=tLBlhp0SA_0&t=22s",
  },
  {
    id: "html-5",
    title: "HTML & CSS Integration",
    category: "HTML",
    instructor: "W3School",
    lessons: 1,
    duration: "2m",
    features: ["Integration"],
    price: "$45",
    rating: 4.3,
    video: "https://www.youtube.com/watch?v=VSwaoQ3TFkQ",
  },

  // ===== CSS (10) =====
  {
    id: "css-1",
    title: "CSS : Build Modern, Responsive & Animated Websites",
    category: "CSS",
    instructor: "Shradha Khanpara",
    lessons: 12,
    duration: "7h 18m",
    features: ["Flexbox", "Grid", "Animations"],
    price: "$59",
    rating: 4.7,
    video: "https://www.youtube.com/watch?v=ESnrn1kAD4E",
  },
  {
    id: "css-2",
    title: "CSS Basics for Beginners",
    category: "CSS",
    instructor: "Harray",
    lessons: 3,
    duration: "11m",
    features: ["Selectors", "Property", "Value"],
    price: "$45",
    rating: 4.5,
    video:
      "https://www.youtube.com/watch?v=ua24185-rcw&list=PLH8iQ-rTfw2-lp7oienYPq9JT3rc-B_9p",
  },
  {
    id: "css-3",
    title: "Variable And Custom Properties",
    category: "CSS",
    instructor: "Harray",
    lessons: 2,
    duration: "10m",
    features: ["Variable", "Property"],
    price: "$55",
    rating: 4.6,
    video:
      "https://www.youtube.com/watch?v=ghlm_94oR90&list=PLH8iQ-rTfw2-lp7oienYPq9JT3rc-B_9p&index=22",
  },
  {
    id: "css-4",
    title: "Ultimate Master Class",
    category: "CSS",
    instructor: "Harray",
    lessons: 6,
    duration: "32m",
    features: ["Grid Layout", "Flexbox", "Responsive"],
    price: "$52",
    rating: 4.5,
    video: "https://www.youtube.com/watch?v=7AgEjgUtho4",
  },
  {
    id: "css-5",
    title: "CSS for Responsive Design",
    category: "CSS",
    instructor: "Harray",
    lessons: 2,
    duration: "11m",
    features: ["Media Queries", "Flexbox", "Typography"],
    price: "$48",
    rating: 4.4,
    video: "https://www.youtube.com/watch?v=eHye3PxH4jU",
  },

  // ===== Tailwind CSS (10) =====
  {
    id: "tailwind-1",
    title:
      "Advanced Tailwind CSS: Utility Classes, Responsive Design & Customization",
    category: "Tailwind CSS",
    instructor: "Harry",
    lessons: 3,
    duration: "18m",
    features: ["Introduction", "Responsive Design"],
    price: "$55",
    rating: 4.8,
    video:
      "https://www.youtube.com/watch?v=L4_jarMnB0c&list=PLu0W_9lII9ahwFDuExCpPFHAK829Wto2O",
  },
  {
    id: "tailwind-2",
    title: "Tailwind CSS Basics",
    category: "Tailwind CSS",
    instructor: "Harray",
    lessons: 6,
    duration: "33m",
    features: ["Setup", "Basic Idea"],
    price: "$42",
    rating: 4.6,
    video: "https://www.youtube.com/watch?v=-g969furGik",
  },
  {
    id: "tailwind-3",
    title: "Hover , Focus & Other States in TailwindCss",
    category: "Tailwind CSS",
    instructor: "Harry",
    lessons: 4,
    duration: "13m",
    features: ["Hover", "Transition", "Buttons"],
    price: "$48",
    rating: 4.7,
    video:
      "https://www.youtube.com/watch?v=R6d5pRFulIk&list=PLu0W_9lII9ahwFDuExCpPFHAK829Wto2O&index=8",
  },
  {
    id: "tailwind-4",
    title: "Tailwind Responsive Design",
    category: "Tailwind CSS",
    instructor: "Harray",
    lessons: 7,
    duration: "17m",
    features: ["Breakpoints", "Layouts"],
    price: "$50",
    rating: 4.5,
    video:
      "https://www.youtube.com/watch?v=WGsiW_-2rZg&list=PLu0W_9lII9ahwFDuExCpPFHAK829Wto2O&index=7",
  },
  {
    id: "tailwind-5",
    title: "Create Mircrosoft Clone with Tailwindcss",
    category: "Tailwind CSS",
    instructor: "Harray",
    lessons: 8,
    duration: "1h 33m",
    features: ["Navbar", "Integration"],
    price: "$60",
    rating: 4.9,
    video:
      "https://www.youtube.com/watch?v=CJ3TNK4lkDU&list=PLu0W_9lII9ahwFDuExCpPFHAK829Wto2O&index=15",
  },
  // ===== Python (10) =====
  {
    id: "python-1",
    title: "Complete Python Learning RoadMap",
    category: "Python",
    instructor: "Shradha Khanpara",
    lessons: 3,
    duration: "13m",
    features: ["Basics", "Understanding", "Road Map"],
    price: "$69",
    rating: 4.9,
    video: "https://www.youtube.com/watch?v=XV-lIaO00H8",
  },
  {
    id: "python-2",
    title: "Python: Learn OOP Concepts",
    category: "Python",
    instructor: "Shradha Khanpara",
    lessons: 11,
    duration: "56m",
    features: ["Class", "Object", "oops", "Constructor"],
    price: "$49",
    rating: 4.6,
    video: "https://www.youtube.com/watch?v=HeW-D6KpDwY",
  },
  {
    id: "python-3",
    title: "Component , Escape Seaquence & Print Statement",
    category: "Python",
    instructor: "Harray",
    lessons: 50,
    duration: "18m",
    features: ["Escape Sequence", "Print Statement"],
    price: "$59",
    rating: 4.8,
    video:
      "https://www.youtube.com/watch?v=qxPMmW93eDs&list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg&index=5",
  },
  {
    id: "python-4",
    title: "MultiThreading in Python",
    category: "Python",
    instructor: "Harray",
    lessons: 4,
    duration: "17m",
    features: ["MultiThreading"],
    price: "$55",
    rating: 4.7,
    video:
      "https://www.youtube.com/watch?v=ICbU6zAKtqQ&list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg&index=97",
  },
  {
    id: "python-5",
    title: "Pandas library in python",
    category: "Python",
    instructor: "Harray",
    lessons: 6,
    duration: "36m",
    features: ["Pandas"],
    price: "$50",
    rating: 4.6,
    video: "https://www.youtube.com/watch?v=E9WGC0SLPVs",
  },
  // ===== JavaScript (10) =====
  {
    id: "js-1",
    title: "Introduction to DOM",
    category: "JavaScript",
    instructor: "Shradha Khanpara",
    lessons: 5,
    duration: "1h 22m",
    features: ["ES6", "DOM Manipulation", "Events"],
    price: "$65",
    rating: 4.8,
    video: "https://www.youtube.com/watch?v=7zcXPCt8Ck0",
  },
  {
    id: "js-2",
    title: "JavaScript for Beginners",
    category: "JavaScript",
    instructor: "Harray",
    lessons: 2,
    duration: "13m",
    features: ["Basics introduction", "Setup"],
    price: "$45",
    rating: 4.5,
    video:
      "https://www.youtube.com/watch?v=ER9SspLe4Hg&list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR",
  },
  {
    id: "js-3",
    title: "introduction to Promises",
    category: "JavaScript",
    instructor: "Harray",
    lessons: 3,
    duration: "13m",
    features: ["Basics Understanding", "Promises", "Closures"],
    price: "$55",
    rating: 4.7,
    video:
      "https://www.youtube.com/watch?v=Dadlf6YsTHA&list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR&index=54",
  },
  {
    id: "js-4",
    title: "Create Spotify Clone Using Javascript",
    category: "JavaScript",
    instructor: "Harray",
    lessons: 12,
    duration: "1h 39m",
    features: ["DOM Projects", "Sportify Clone"],
    price: "$50",
    rating: 4.6,
    video:
      " https://www.youtube.com/watch?v=ANzPM5-lwXc&list=PLu0W_9lII9aiQiOwthuSvinxoflmhRxM3&index=1",
  },
  {
    id: "js-5",
    title: "Cookies in Javascript",
    category: "JavaScript",
    instructor: "Harray",
    lessons: 7,
    duration: "15m",
    features: ["Cookies"],
    price: "$48",
    rating: 4.5,
    video:
      "https://www.youtube.com/watch?v=sHrwueeeMmY&list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR&index=68",
  },

  // ===== React JS (10) =====
  {
    id: "react-1",
    title: "React JS Development:Hooks & State Management",
    category: "React JS",
    instructor: "Harray",
    lessons: 2,
    duration: "11m",
    features: ["Hooks", "State"],
    price: "$70",
    rating: 4.9,
    video: " https://www.youtube.com/watch?v=zHoWgJD0jw4",
  },
  {
    id: "react-2",
    title: "Understanding jsx",
    category: "React JS",
    instructor: "Harray",
    lessons: 4,
    duration: "26m",
    features: ["JSX", "Components", "Props"],
    price: "$50",
    rating: 4.6,
    video:
      "https://www.youtube.com/watch?v=JvC7aA24m4Q&list=PLu0W_9lII9agx66oZnT6IyhcMIbUMNMdt&index=4",
  },
  {
    id: "react-3",
    title: "Create Enable Dark Mode Button Using UseState",
    category: "React JS",
    instructor: "Harray",
    lessons: 9,
    duration: "19m",
    features: ["Dark Mode", "Light Mode"],
    price: "$65",
    rating: 4.8,
    video:
      "https://www.youtube.com/watch?v=Sx2y4TjRZ9g&list=PLu0W_9lII9agx66oZnT6IyhcMIbUMNMdt&index=10",
  },
  {
    id: "react-4",
    title: "Creating a Middleware to decoder user form a JWT",
    category: "React JS",
    instructor: "Harray",
    lessons: 3,
    duration: "14m",
    features: ["Middleware", "Decode"],
    price: "$55",
    rating: 4.7,
    video:
      "https://www.youtube.com/watch?v=qY0PZ-z61EQ&list=PLu0W_9lII9agx66oZnT6IyhcMIbUMNMdt&index=51",
  },
  {
    id: "react-5",
    title: "Adding Previous & Next Buttons to populate NewsItems ",
    category: "React JS",
    instructor: "Harray",
    lessons: 6,
    duration: "16m",
    features: ["Previous Button", "Next Button"],
    price: "$58",
    rating: 4.7,
    video:
      "https://www.youtube.com/watch?v=FOjrXXdiCMs&list=PLu0W_9lII9agx66oZnT6IyhcMIbUMNMdt&index=28",
  },
];
export default CourseCardData;
